name: Tests

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GOPROXY: ""

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write # Needed to push docker images to GitHub Container Registry
      contents: read
    steps:
    - name: Checkout project
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v6.0.2
      with:
        fetch-depth: 0

    - name: Setup Go environment
      uses: actions/setup-go@v6.2.0
      with:
        # Path to the go.mod or go.work file.
        go-version-file: ./go.mod
        # Used to specify the path to a dependency file - go.sum
        cache-dependency-path: ./go.sum

    - name: Run tests before releasing
      run: CGO_ENABLED=0 make test

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta-data
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    # TODO: Handle multi arch image
    - name: Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        build-args: |
          GOPROXY=${{ env.GOPROXY }}
        push: true
        tags: ${{ steps.meta-data.outputs.tags }}
        labels: ${{ steps.meta-data.outputs.labels }}
